import { Product, CarouselItem, StoreInfo, NavLink } from "@/types";

// Store Information
export const STORE_INFO: StoreInfo = {
  name: "Sosina Mart",
  phone: "470-359-7924",
  email: "info@sosinamart.com",
  address: "6330 Lawrenceville Hwy, Tucker, GA 30084",
  website: "www.sosinamart.com",
  socialLinks: [
    { platform: "Facebook", url: "https://facebook.com/sosinamart", icon: "facebook" },
    { platform: "Instagram", url: "https://instagram.com/sosinamart", icon: "instagram" },
    { platform: "Twitter", url: "https://twitter.com/sosinamart", icon: "twitter" },
    { platform: "YouTube", url: "https://youtube.com/sosinamart", icon: "youtube" },
    { platform: "TikTok", url: "https://tiktok.com/@sosinamart", icon: "tiktok" },
  ],
};

// Navigation Links
export const NAV_LINKS: NavLink[] = [
  { label: "Food", href: "#food-section", category: "food" },
  { label: "Kitchenware", href: "#kitchenware-section", category: "kitchenware" },
  { label: "Artifacts", href: "#artifacts-section", category: "artifacts" },
];

// Products Data
export const PRODUCTS: Product[] = [
  // Food & Coffee (15 items)
  {
    id: "f1",
    name: "Berbere Spice Blend",
    description: "Traditional Ethiopian spice blend with chili peppers, garlic, and aromatic spices",
    price: 12.99,
    category: "food",
    image: "/images/products/berbere.jpg",
    inStock: true,
    featured: true,
  },
  {
    id: "f2",
    name: "Mitmita Spice",
    description: "Fiery Ethiopian chili powder blend",
    price: 10.99,
    category: "food",
    image: "/images/products/mitmita.jpg",
    inStock: true,
  },
  {
    id: "f3",
    name: "Shiro Powder",
    description: "Ground chickpea flour with spices for traditional stew",
    price: 8.99,
    category: "food",
    image: "/images/products/shiro.jpg",
    inStock: true,
    featured: true,
  },
  {
    id: "f4",
    name: "Fresh Injera (10 pack)",
    description: "Authentic fermented teff flatbread",
    price: 15.99,
    category: "food",
    image: "/images/products/injera.jpg",
    inStock: true,
    featured: true,
  },
  {
    id: "f5",
    name: "Yirgacheffe Coffee Beans",
    description: "Premium Ethiopian coffee from Yirgacheffe region",
    price: 18.99,
    category: "food",
    image: "/images/products/yirgacheffe.jpg",
    inStock: true,
    featured: true,
  },
  {
    id: "f6",
    name: "Misir Lentils",
    description: "Red split lentils for traditional Misir Wot",
    price: 7.99,
    category: "food",
    image: "/images/products/misir.jpg",
    inStock: true,
  },
  {
    id: "f7",
    name: "Korerima (Ethiopian Cardamom)",
    description: "Aromatic spice essential for Ethiopian cuisine",
    price: 9.99,
    category: "food",
    image: "/images/products/korerima.jpg",
    inStock: true,
  },
  {
    id: "f8",
    name: "Teff Flour (1kg)",
    description: "Gluten-free ancient grain flour for injera",
    price: 11.99,
    category: "food",
    image: "/images/products/teff.jpg",
    inStock: true,
  },
  {
    id: "f9",
    name: "Ethiopian Honey",
    description: "Pure raw honey from Ethiopian highlands",
    price: 24.99,
    category: "food",
    image: "/images/products/honey.jpg",
    inStock: true,
  },
  {
    id: "f10",
    name: "Awaze Paste",
    description: "Spicy Ethiopian condiment paste",
    price: 8.99,
    category: "food",
    image: "/images/products/awaze.jpg",
    inStock: true,
  },
  {
    id: "f11",
    name: "Niter Kibbeh (Spiced Butter)",
    description: "Traditional Ethiopian clarified butter with spices",
    price: 14.99,
    category: "food",
    image: "/images/products/niter-kibbeh.jpg",
    inStock: true,
  },
  {
    id: "f12",
    name: "Harar Coffee Beans",
    description: "Wild-grown coffee from Harar region",
    price: 17.99,
    category: "food",
    image: "/images/products/harar-coffee.jpg",
    inStock: true,
  },
  {
    id: "f13",
    name: "Fenugreek Seeds",
    description: "Essential spice for Ethiopian cooking",
    price: 5.99,
    category: "food",
    image: "/images/products/fenugreek.jpg",
    inStock: true,
  },
  {
    id: "f14",
    name: "Black Cumin (Tikur Azmud)",
    description: "Ethiopian black cumin seeds",
    price: 7.99,
    category: "food",
    image: "/images/products/black-cumin.jpg",
    inStock: true,
  },
  {
    id: "f15",
    name: "Dried Split Peas",
    description: "Yellow split peas for traditional dishes",
    price: 6.99,
    category: "food",
    image: "/images/products/split-peas.jpg",
    inStock: true,
  },

  // Kitchenware (15 items)
  {
    id: "k1",
    name: "Clay Jebena Coffee Pot",
    description: "Traditional Ethiopian clay coffee pot for authentic coffee ceremony",
    price: 49.99,
    category: "kitchenware",
    image: "/images/products/jebena.jpg",
    inStock: true,
    featured: true,
  },
  {
    id: "k2",
    name: "Mitad Injera Griddle",
    description: "Large clay griddle for making traditional injera bread",
    price: 89.99,
    category: "kitchenware",
    image: "/images/products/mitad.jpg",
    inStock: true,
    featured: true,
  },
  {
    id: "k3",
    name: "Mesob Serving Basket",
    description: "Colorful woven basket for serving injera and stews",
    price: 129.99,
    category: "kitchenware",
    image: "/images/products/mesob.jpg",
    inStock: true,
    featured: true,
  },
  {
    id: "k4",
    name: "Coffee Cup Set (Sini)",
    description: "Set of 6 traditional handleless coffee cups",
    price: 34.99,
    category: "kitchenware",
    image: "/images/products/coffee-cups.jpg",
    inStock: true,
    featured: true,
  },
  {
    id: "k5",
    name: "Coffee Roasting Pan",
    description: "Long-handled pan for roasting coffee beans",
    price: 29.99,
    category: "kitchenware",
    image: "/images/products/roasting-pan.jpg",
    inStock: true,
  },
  {
    id: "k6",
    name: "Mortar & Pestle (Mukecha)",
    description: "Wooden mortar and pestle for grinding spices",
    price: 39.99,
    category: "kitchenware",
    image: "/images/products/mortar-pestle.jpg",
    inStock: true,
  },
  {
    id: "k7",
    name: "Clay Cooking Pot (Shekla)",
    description: "Traditional clay pot for cooking stews",
    price: 44.99,
    category: "kitchenware",
    image: "/images/products/clay-pot.jpg",
    inStock: true,
  },
  {
    id: "k8",
    name: "Woven Serving Tray",
    description: "Colorful handwoven tray for serving food",
    price: 24.99,
    category: "kitchenware",
    image: "/images/products/serving-tray.jpg",
    inStock: true,
  },
  {
    id: "k9",
    name: "Incense Burner (Itan)",
    description: "Traditional clay incense burner for coffee ceremony",
    price: 19.99,
    category: "kitchenware",
    image: "/images/products/incense-burner.jpg",
    inStock: true,
  },
  {
    id: "k10",
    name: "Rekebot Coffee Tray",
    description: "Wooden tray stand for serving coffee ceremony",
    price: 59.99,
    category: "kitchenware",
    image: "/images/products/rekebot.jpg",
    inStock: true,
  },
  {
    id: "k11",
    name: "Injera Basket (Sefed)",
    description: "Flat woven basket for serving injera",
    price: 34.99,
    category: "kitchenware",
    image: "/images/products/injera-basket.jpg",
    inStock: true,
  },
  {
    id: "k12",
    name: "Spice Container Set",
    description: "Set of traditional containers for storing spices",
    price: 29.99,
    category: "kitchenware",
    image: "/images/products/spice-containers.jpg",
    inStock: true,
  },
  {
    id: "k13",
    name: "Ethiopian Tea Kettle",
    description: "Traditional kettle for brewing tea",
    price: 39.99,
    category: "kitchenware",
    image: "/images/products/tea-kettle.jpg",
    inStock: true,
  },
  {
    id: "k14",
    name: "Berbere Grinder",
    description: "Stone grinder for making fresh berbere spice",
    price: 54.99,
    category: "kitchenware",
    image: "/images/products/grinder.jpg",
    inStock: true,
  },
  {
    id: "k15",
    name: "Complete Coffee Ceremony Set",
    description: "Full set including jebena, cups, tray, and incense burner",
    price: 149.99,
    category: "kitchenware",
    image: "/images/products/coffee-set.jpg",
    inStock: true,
  },

  // Artifacts & Accessories (15 items)
  {
    id: "a1",
    name: "Ethiopian Coptic Cross",
    description: "Hand-crafted brass cross with traditional design",
    price: 45.99,
    category: "artifacts",
    image: "/images/products/coptic-cross.jpg",
    inStock: true,
    featured: true,
  },
  {
    id: "a2",
    name: "Beaded Necklace Set",
    description: "Traditional amber and gold beaded jewelry",
    price: 34.99,
    category: "artifacts",
    image: "/images/products/beaded-necklace.jpg",
    inStock: true,
    featured: true,
  },
  {
    id: "a3",
    name: "Traditional Mesob Basket",
    description: "Large woven basket for serving injera",
    price: 129.99,
    category: "artifacts",
    image: "/images/products/mesob.jpg",
    inStock: true,
    featured: true,
  },
  {
    id: "a4",
    name: "Clay Coffee Pot (Jebena)",
    description: "Traditional Ethiopian coffee brewing pot",
    price: 49.99,
    category: "artifacts",
    image: "/images/products/jebena.jpg",
    inStock: true,
    featured: true,
  },
  {
    id: "a5",
    name: "Woven Wall Art",
    description: "Colorful decorative wall hanging",
    price: 79.99,
    category: "artifacts",
    image: "/images/products/wall-art.jpg",
    inStock: true,
  },
  {
    id: "a6",
    name: "Mitad Grill (Injera Pan)",
    description: "Traditional clay griddle for making injera",
    price: 89.99,
    category: "artifacts",
    image: "/images/products/mitad.jpg",
    inStock: true,
  },
  {
    id: "a7",
    name: "Hand-carved Wooden Cross",
    description: "Artisan wooden Ethiopian cross",
    price: 65.99,
    category: "artifacts",
    image: "/images/products/wooden-cross.jpg",
    inStock: true,
  },
  {
    id: "a8",
    name: "Silver Coptic Cross Pendant",
    description: "Sterling silver cross necklace",
    price: 89.99,
    category: "artifacts",
    image: "/images/products/silver-cross.jpg",
    inStock: true,
  },
  {
    id: "a9",
    name: "Coffee Ceremony Set",
    description: "Complete set for traditional coffee ceremony",
    price: 149.99,
    category: "artifacts",
    image: "/images/products/coffee-set.jpg",
    inStock: true,
  },
  {
    id: "a10",
    name: "Woven Serving Tray",
    description: "Colorful handwoven tray",
    price: 39.99,
    category: "artifacts",
    image: "/images/products/serving-tray.jpg",
    inStock: true,
  },
  {
    id: "a11",
    name: "Traditional Drum",
    description: "Authentic Ethiopian kebero drum",
    price: 119.99,
    category: "artifacts",
    image: "/images/products/drum.jpg",
    inStock: true,
  },
  {
    id: "a12",
    name: "Ethiopian Map Wall Art",
    description: "Decorative map artwork",
    price: 59.99,
    category: "artifacts",
    image: "/images/products/map-art.jpg",
    inStock: true,
  },
  {
    id: "a13",
    name: "Brass Incense Burner",
    description: "Traditional incense holder",
    price: 44.99,
    category: "artifacts",
    image: "/images/products/incense-burner.jpg",
    inStock: true,
  },
  {
    id: "a14",
    name: "Leather Bible Cover",
    description: "Hand-tooled leather cover",
    price: 79.99,
    category: "artifacts",
    image: "/images/products/bible-cover.jpg",
    inStock: true,
  },
  {
    id: "a15",
    name: "Colorful Basket Set (3pc)",
    description: "Set of three decorative baskets",
    price: 69.99,
    category: "artifacts",
    image: "/images/products/basket-set.jpg",
    inStock: true,
  },
];

// Get products by category
export const getProductsByCategory = (category: string): Product[] => {
  return PRODUCTS.filter((p) => p.category === category);
};

// Get featured products
export const getFeaturedProducts = (): Product[] => {
  return PRODUCTS.filter((p) => p.featured);
};

// Get product by ID
export const getProductById = (id: string): Product | undefined => {
  return PRODUCTS.find((p) => p.id === id);
};

// Carousel Items - 20 Ethiopian Traditional Clothing Videos
export const CAROUSEL_ITEMS: CarouselItem[] = [
  { id: "car1", type: "video", src: "/videos/vid-1.mp4", title: "Traditional Elegance" },
  { id: "car2", type: "video", src: "/videos/vid-2.mp4", title: "Habesha Beauty" },
  { id: "car3", type: "video", src: "/videos/vid-3.mp4", title: "Cultural Fashion" },
  { id: "car4", type: "video", src: "/videos/vid-4.mp4", title: "Ethiopian Style" },
  { id: "car5", type: "video", src: "/videos/vid-5.mp4", title: "Traditional Dress" },
  { id: "car6", type: "video", src: "/videos/vid-6.mp4", title: "Heritage Collection" },
  { id: "car7", type: "video", src: "/videos/vid-7.mp4", title: "Kemis Showcase" },
  { id: "car8", type: "video", src: "/videos/vid-8.mp4", title: "Tilet Embroidery" },
  { id: "car9", type: "video", src: "/videos/vid-9.mp4", title: "Festival Wear" },
  { id: "car10", type: "video", src: "/videos/vid-10.mp4", title: "Wedding Fashion" },
  { id: "car11", type: "video", src: "/videos/vid-11.mp4", title: "Modern Traditional" },
  { id: "car12", type: "video", src: "/videos/vid-12.mp4", title: "Elegant White" },
  { id: "car13", type: "video", src: "/videos/vid-13.mp4", title: "Cultural Pride" },
  { id: "car14", type: "video", src: "/videos/vid-14.mp4", title: "Ethiopian Grace" },
  { id: "car15", type: "video", src: "/videos/vid-15.mp4", title: "Traditional Art" },
  { id: "car16", type: "video", src: "/videos/vid-16.mp4", title: "Handwoven Beauty" },
  { id: "car17", type: "video", src: "/videos/vid-17.mp4", title: "Classic Design" },
  { id: "car18", type: "video", src: "/videos/vid-18.mp4", title: "Timeless Fashion" },
  { id: "car19", type: "video", src: "/videos/vid-19.mp4", title: "Runway Style" },
  { id: "car20", type: "video", src: "/videos/vid-20.mp4", title: "Grand Collection" },
];

// Section titles
export const SECTION_TITLES = {
  carousel: "Ethiopia's Traditional Clothing",
  food: "Food & Coffee Essentials",
  kitchenware: "Traditional Kitchenware",
  artifacts: "Cultural Artifacts & Accessories",
};
